project:
  type: website
  output-dir: docs      

website:
  description: "A blog built with Quarto"
  site-url: https://iSmailTG.github.io/inference-engineering
  title: "inference-engineering"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/iSmailTG  
      - icon: twitter
        href: https://twitter.com/taghchti

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
